### ISSUE TITLE
move_to command should come after the check for the scan_start time

### ISSUE THREAD

**Issue by samdayweiss** [simonsobs/scheduler#84]
Can we move all `move_to` commands inside the `if` statement determining whether or not to start a scan? Otherwise, the if statement does not really save us time for restarting schedules.

**Comment by kmharrington** [comment]
We talked about this at the site computing call and we're thinking not to implement this in favor of trying to get to the more final scheduler form where we can auto-pull the next schedule from a server (which would include checking the current state of the telescope). The original if statements are there so that if something is started at the wrong time we don't have a lot of commands piling up to smurf for turning streams on and off, because recovering from that is super annoying. Trying to add in lots of moves inside the if-statements makes it really hard to be sure of the state of the telescope at any specific time and implementing something that won't lead to more errors will be a lot of work, so better to spend the time going toward auto-generation of the schedules. 

I did just go in and set a tolerance on the first run.wait_until (https://github.com/simonsobs/scheduler/pull/99), this will cause nextline to throw and error if the schedule is started more than an hour offset from when it's intended to be started. Obviously folks can change that time when they start a schedule late, and that way changing the schedule and removing missed scans will be required.
