### ISSUE TITLE
IV curves should happen after all elevation changes

### ISSUE THREAD

**Issue by samdayweiss** [simonsobs/scheduler#85]
For satp3 our nominal CMB scan elevation is 60 degrees. If, for example, a planet scan happens at elevation 48, right now when the schedule resumes CMB operations at 60, no IV curve is done before the scan begins. While this may be okay for low PWV days, I think a good general rule is to re-bias after any change in elevation > 5 degrees. Can this be implemented in the scheduler?

**Comment by kmharrington** [comment]
The issue here is the difference in logic between the sat.det_setup operation and the satp3.det_setup operation. See:

https://github.com/simonsobs/scheduler/blob/4b30f6d0b7d950e788ca48238a7596b84b77113b/src/schedlib/policies/sat.py#L186

and 

https://github.com/simonsobs/scheduler/blob/4b30f6d0b7d950e788ca48238a7596b84b77113b/src/schedlib/policies/satp3.py#L161 

We should probably work out how to merge these in the code. Everything should be equal between the two telescopes except the list of commands that are added at a det_setup block (satp3 will have boresight rotation disabled inside the configs so that if statement will never run). We can define `sat.det_setup` to accept a command list and then each telescope could pass through their favorite. 

Is anyone able to take that on?
